"""
ParaView Contour GIF Maker
==========================
This script compiles the PNG images generated by `paraview_contour_exporter.py` 
into animated GIFs, grouping them by variable and camera view across all Angles of Attack (Velocity).

Supports multiple IMAGE_OUTPUT_DIRS with 'Highest Version Wins' deduplication:
when multiple directories contain frames for the same Velocity/variable/view,
only the frame from the highest-versioned config is used.

Usage:
    Run this script using STANDARD python, not pvpython.
    python paraview_gif_maker.py
"""

import os
import re
import glob
from collections import defaultdict
from PIL import Image

# ============================================================
# CONFIGURATION
# ============================================================

# List of image output directories from paraview_contour_exporter.py.
# When multiple directories share the same identity (velocity.mesh.turbulence.grid)
# but differ in version, only the highest version's frames are used per Velocity.
IMAGE_OUTPUT_DIRS = [
    r"C:\Users\lukek\OneDrive\Documents\Thesis\NACA_2414_2D\Fluent\Directories\Processed_Data\Singular_Data\2414.6.5\5.6.1.1.G\Countour_Plots\ParaView",
    r"C:\Users\lukek\OneDrive\Documents\Thesis\NACA_2414_2D\Fluent\Directories\Processed_Data\Singular_Data\2414.6.5\5.6.1.3.G\Countour_Plots\ParaView",
    r"C:\Users\lukek\OneDrive\Documents\Thesis\NACA_2414_2D\Fluent\Directories\Processed_Data\Singular_Data\2414.6.5\5.6.1.5.G\Countour_Plots\ParaView",
    r"C:\Users\lukek\OneDrive\Documents\Thesis\NACA_2414_2D\Fluent\Directories\Processed_Data\Singular_Data\2414.6.5\5.6.1.6.G\Countour_Plots\ParaView",
    r"C:\Users\lukek\OneDrive\Documents\Thesis\NACA_2414_2D\Fluent\Directories\Processed_Data\Singular_Data\2414.6.5\5.6.1.7.G\Countour_Plots\ParaView",
    r"C:\Users\lukek\OneDrive\Documents\Thesis\NACA_2414_2D\Fluent\Directories\Processed_Data\Singular_Data\2414.6.5\5.6.1.8.G\Countour_Plots\ParaView",
]

# Configuration names (must match the order/length of IMAGE_OUTPUT_DIRS)
CONFIG_NAMES = [
    "5.6.1.1.G",
    "5.6.1.3.G",
    "5.6.1.5.G",
    "5.6.1.6.G",
    "5.6.1.7.G",
    "5.6.1.8.G",
]

# List of Velocity values to include in the GIF. Leave empty [] to include ALL found images.
VELOCITY_LIST = []

# Where to save the GIFs
GIF_OUTPUT_DIR = r"C:\Users\lukek\OneDrive\Documents\Thesis\NACA_2414_2D\Fluent\Directories\Processed_Data\Contour_Exports\GIFS\5.6\5.6.1.G"

# Time to show each frame in milliseconds (e.g., 500 = 0.5 seconds per Velocity)
FRAME_DURATION = 250

# ============================================================
# SCRIPT LOGIC
# ============================================================

def parse_identity_and_version(config_name):
    """
    Extract identity (everything except version) and version number from a config name.
    
    Uses the same 5-part naming schema as main.py:
        velocity.mesh.turbulence.version.grid  (e.g. 5.6.1.1.G)
    
    For 4-part names without a grid suffix:
        velocity.mesh.turbulence.version       (e.g. 4.3.1.2)
    
    Returns:
        (identity_tuple, version_number)
        identity_tuple: (velocity, mesh, turbulence, grid_or_None) — uniquely identifies
                        the physical setup ignoring version
        version_number: int version number (higher wins)
    """
    parts = config_name.split('.')
    
    # Detect grid suffix (last part is 'G' or 'NG')
    grid = None
    numeric_parts = parts
    if parts[-1] in ('G', 'NG'):
        grid = parts[-1]
        numeric_parts = parts[:-1]
    
    # Parse positions: velocity(0), mesh(1), turbulence(2), version(3)
    velocity = numeric_parts[0] if len(numeric_parts) > 0 else '?'
    mesh     = numeric_parts[1] if len(numeric_parts) > 1 else '?'
    turb     = numeric_parts[2] if len(numeric_parts) > 2 else '?'
    
    try:
        version = int(numeric_parts[3]) if len(numeric_parts) > 3 else 0
    except ValueError:
        version = 0
    
    identity = (velocity, mesh, turb, grid)
    return identity, version


def collect_frames_with_version_priority(image_output_dirs, config_names, velocity_filter):
    """
    Scan all image directories and collect frames, applying 'Highest Version Wins'.
    
    When multiple directories share the same identity but differ in version,
    for each (Velocity, variable, view) only the frame from the highest version is kept.
    
    Returns:
        dict: {suffix: [(velocity_val, image_path), ...]}
              where suffix is e.g. "Pressure_Static_leading_edge_zoom"
    """
    # Build version lookup: identity -> highest (version, dir_index)
    identity_versions = defaultdict(list)
    for idx, config_name in enumerate(config_names):
        identity, version = parse_identity_and_version(config_name)
        identity_versions[identity].append((version, idx))
    
    # For each identity, determine the winning version
    # winner_map: identity -> (winning_version, winning_index)
    winner_map = {}
    for identity, candidates in identity_versions.items():
        candidates.sort(key=lambda x: x[0], reverse=True)
        winner_map[identity] = candidates[0]
        
        if len(candidates) > 1:
            winner_ver, winner_idx = candidates[0]
            for loser_ver, loser_idx in candidates[1:]:
                print(f"  [SUPPRESSED] {config_names[loser_idx]} (v{loser_ver}) "
                      f"overridden by {config_names[winner_idx]} (v{winner_ver})")
    
    # Now collect frames, but per (identity, velocity, suffix) keep only the best version
    # frame_candidates: (identity, velocity_val, suffix) -> [(version, path), ...]
    frame_candidates = defaultdict(list)
    
    for idx, (image_dir, config_name) in enumerate(zip(image_output_dirs, config_names)):
        if not os.path.exists(image_dir):
            print(f"  [WARNING] Directory not found: {image_dir}")
            continue
        
        identity, version = parse_identity_and_version(config_name)
        
        search_pattern = os.path.join(image_dir, "velocity_*", "*.png")
        image_paths = glob.glob(search_pattern)
        
        for path in image_paths:
            filename = os.path.basename(path)
            
            if "_velocity_" not in filename:
                continue
            
            parts = filename.split("_velocity_")
            if len(parts) < 2:
                continue
            
            subparts = parts[1].split("_", 1)
            if len(subparts) < 2:
                continue
            
            velocity_str = subparts[0]
            suffix = subparts[1].replace(".png", "")
            
            try:
                velocity_val = float(velocity_str)
            except ValueError:
                continue
            
            # Apply Velocity filter
            if velocity_filter and float(velocity_val) not in [float(x) for x in velocity_filter]:
                continue
            
            frame_candidates[(identity, velocity_val, suffix)].append((version, path))
    
    # Resolve: for each (identity, velocity, suffix), pick the highest version frame
    groups = defaultdict(list)
    
    for (identity, velocity_val, suffix), candidates in frame_candidates.items():
        candidates.sort(key=lambda x: x[0], reverse=True)
        best_version, best_path = candidates[0]
        groups[suffix].append((velocity_val, best_path))
    
    return groups


def main():
    print("=" * 60)
    print("ParaView Contour GIF Maker")
    print("=" * 60)
    
    # Validate config
    if len(IMAGE_OUTPUT_DIRS) != len(CONFIG_NAMES):
        print("[ERROR] IMAGE_OUTPUT_DIRS and CONFIG_NAMES must have the same number of entries!")
        return
    
    os.makedirs(GIF_OUTPUT_DIR, exist_ok=True)
    
    print(f"\nScanning {len(IMAGE_OUTPUT_DIRS)} directories for frames...")
    for i, (d, c) in enumerate(zip(IMAGE_OUTPUT_DIRS, CONFIG_NAMES)):
        print(f"  [{i+1}] {c} -> {d}")
    
    # Collect frames with version deduplication
    print("\nApplying 'Highest Version Wins' frame selection...")
    groups = collect_frames_with_version_priority(IMAGE_OUTPUT_DIRS, CONFIG_NAMES, VELOCITY_LIST)
    
    if not groups:
        print("[WARNING] No PNG images found to animate!")
        return
    
    total_frames = sum(len(v) for v in groups.values())
    print(f"Found {total_frames} frames across {len(groups)} animation groups.")
    
    # Determine a label for the GIF filenames
    # Use the highest-versioned config name as the label
    best_config = CONFIG_NAMES[0]
    best_version = 0
    for config_name in CONFIG_NAMES:
        _, version = parse_identity_and_version(config_name)
        if version > best_version:
            best_version = version
            best_config = config_name
    
    # Generate GIFs
    gifs_created = 0
    
    for suffix, img_list in groups.items():
        # Sort the frames so the GIF goes from lowest Velocity to highest Velocity
        img_list.sort(key=lambda x: x[0])
        
        print(f"\nCreating GIF for: {suffix}")
        print(f"  -> Frames: {[x[0] for x in img_list]}")
        
        frames = []
        target_size = None
        for velocity_val, path in img_list:
            img = Image.open(path)
            if target_size is None:
                target_size = img.size
            elif img.size != target_size:
                img = img.resize(target_size, Image.LANCZOS)
            frames.append(img)
            
        if frames:
            gif_filename = os.path.join(GIF_OUTPUT_DIR, f"{best_config}_Animated_{suffix}.gif")
            
            # Save the frames as a looping animated GIF
            frames[0].save(
                gif_filename,
                save_all=True,
                append_images=frames[1:],
                duration=FRAME_DURATION,
                loop=0  # 0 means loop forever
            )
            print(f"  -> Saved: {gif_filename}")
            gifs_created += 1

    print("\n" + "=" * 60)
    print(f"[OK] Successfully created {gifs_created} animated GIFs!")
    print(f"Location: {GIF_OUTPUT_DIR}")

if __name__ == "__main__":
    main()
